version: "3"

services:
  gitea:
    image: gitea/gitea   
    environment:
    - USER_UID: ${USER_UID}
    - USER_GID: ${USER_GID}
    - GITEA__database__DB_TYPE: ${GITEA__database__DB_TYPE}
    - GITEA__database__HOST: ${GITEA__database__HOST}
    - GITEA__database__NAME: ${GITEA__database__NAME}
    - GITEA__database__USER: ${GITEA__database__USER}
    - GITEA__database__PASSWD: ${GITEA__database__PASSWD}
    networks:
    - frontend
    - backend    
    ports:
    - "3000:3000"
    - "222:22"
    depends_on:
    - db
    volumes:
    - nfs_gitea_app:/data

  db:
    image: mysql:8         
    environment:
    - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER: ${MYSQL_USER}
    - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    - MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - backend
    volumes:
    - nfs_gitea_db:/var/lib/mysql

networks:
  frontend:
  backend:
    
volumes:
  nfs_gitea_app:
  nfs_gitea_db:
