version: "3"

services:
  db:
    image: mysql:8
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M      
    environment:
    - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER: ${MYSQL_USER}
    - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    - MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - backend

networks:
  frontend:    
  backend:
    