version: "3"

services:
  gitea:
    image: gitea/gitea:1.16.4
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M      
    environment:
    - USER_UID: ${USER_UID}
    - USER_GID: ${USER_GID}
    - GITEA__database__DB_TYPE: ${GITEA__database__DB_TYPE}
    - GITEA__database__HOST: ${GITEA__database__HOST}
    - GITEA__database__NAME: ${GITEA__database__NAME}
    - GITEA__database__USER: ${GITEA__database__USER}
    - GITEA__database__PASSWD: ${GITEA__database__PASSWD}
    networks:
    - frontend
    - backend    
    ports:
    - "3000:3000"
    - "222:22"
    depends_on:
    - db

  db:
    image: mysql:8
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M      
    environment:
    - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER: ${MYSQL_USER}
    - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    - MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - backend

networks:
  frontend:
    external: true
  backend:
    external: true