version: "3"

services:
  db:
    image: mysql:8         
    environment:
    - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER: ${MYSQL_USER}
    - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    - MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - backend

networks:
  backend:    